name = "tantric-plants"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "tantric-plants-db"
database_id = "703f753f-07a5-473f-804d-7c3a8470eec8"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "tantric-plants-photos"
